CREATE OR REPLACE TABLE WISE_TASK_BUILD AS (
WITH 

EXPERIENCE_DATE_FIX AS (
SELECT DISTINCT 
A.USER_ID,
MIN(UPDATED_DT) AS DATE_FIX_DT,
FROM 
wise_funnel_events_regional A
INNER JOIN (SELECT DISTINCT USER_ID FROM wise_funnel_events_regional WHERE EXPERIENCE = 'New') B
ON A.USER_ID=B.USER_ID
WHERE EVENT_NAME = 'Transfer Transferred'
GROUP BY 1
)  --SELECT * FROM  EXPERIENCE_DATE_FIX WHERE USER_ID = 1556990

, BUILD AS (
SELECT 
RD.EVENT_NAME,
CASE
	WHEN RD.EVENT_NAME = 'Transfer Created'THEN 1 
	WHEN RD.EVENT_NAME = 'Transfer Funded' THEN 2 
	WHEN RD.EVENT_NAME = 'Transfer Transferred' THEN 3 
END AS EVENT_ORDER,
RD.DT,
RD.UPDATED_DT,
RD.EXPERIENCE,
DF.DATE_FIX_DT,
RD.USER_ID,
RD.REGION,
RD.PLATFORM,
RD.TRANSFER_ID,
CASE 
WHEN RD.EXPERIENCE = 'Existing' AND RD.DT<=DF.DATE_FIX_DT THEN 'New' --If Experience='Existing' but the user has New appearing at a later date
WHEN RD.EXPERIENCE = 'New' AND RD.DT>DF.DATE_FIX_DT THEN 'Existing' --If Experience='Existing' but the user has New appearing at a later date
ELSE RD.EXPERIENCE
end AS EXPERIENCE_FIX,

CASE
	WHEN RD.EXPERIENCE = 'New' THEN 1 
	WHEN RD.EXPERIENCE = 'Existing' THEN 1 
END AS EXPERIENCE_ORDER,

FROM wise_funnel_events_regional RD
LEFT JOIN EXPERIENCE_DATE_FIX DF
ON DF.USER_ID=RD.USER_ID)

SELECT EVENT_NAME,DT,USER_ID,REGION,PLATFORM,EXPERIENCE_FIX AS EXPERIENCE, UPDATED_DT,TRANSFER_ID FROM BUILD -- WHERE USER_ID = 1714123
ORDER BY USER_ID, UPDATED_DT,EXPERIENCE_ORDER ,EVENT_ORDER)
