CREATE OR REPLACE TABLE FUNNEL_BUILD AS 


SELECT 
DISTINCT 
A.DT,
B.REGION,
C.EXPERIENCE,
D.PLATFORM,
E.USER_ID
FROM WISE_FUNNEL_EVENTS_REGIONAL A
FULL JOIN
(SELECT DISTINCT REGION FROM WISE_FUNNEL_EVENTS_REGIONAL) B 
ON 1=1

FULL JOIN
(SELECT DISTINCT EXPERIENCE FROM WISE_FUNNEL_EVENTS_REGIONAL) C 
ON 1=1

FULL JOIN
(SELECT DISTINCT PLATFORM FROM WISE_FUNNEL_EVENTS_REGIONAL) D  
ON 1=1




